//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public Addresses()
        {
            this.Engagements = new HashSet<Engagements>();
        }
    
        public int Id { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string Street3 { get; set; }
        public string Suburb { get; set; }
        public StateName StateID { get; set; }
        public string Postcode { get; set; }
    
        public virtual Agencies Agency { get; set; }
        public virtual Companies Company { get; set; }
        public virtual ICollection<Engagements> Engagements { get; set; }
    }
}
