//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencies
    {
        public Agencies()
        {
            this.Consultants = new HashSet<Consultants>();
            this.Engagements = new HashSet<Engagements>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Addresses Address { get; set; }
        public virtual ICollection<Consultants> Consultants { get; set; }
        public virtual ICollection<Engagements> Engagements { get; set; }
    }
}
