//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engagements
    {
        public Engagements()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public int Id { get; set; }
        public System.DateTime Commencement { get; set; }
        public Nullable<System.DateTime> Completion { get; set; }
        public int AgenciesId { get; set; }
        public int ConsultantsId { get; set; }
        public int CompaniesId { get; set; }
        public int AddressesId { get; set; }
        public int PeopleId { get; set; }
    
        public virtual Agencies Agency { get; set; }
        public virtual Consultants Consultant { get; set; }
        public virtual Companies Company { get; set; }
        public virtual Addresses Address { get; set; }
        public virtual People Person { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
