//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public People()
        {
            this.Engagements = new HashSet<Engagements>();
            this.Projects = new HashSet<Projects>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int CompaniesId { get; set; }
    
        public virtual Companies Company { get; set; }
        public virtual ICollection<Engagements> Engagements { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
