//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int PeopleId { get; set; }
        public int EngagementsId { get; set; }
    
        public virtual People Person { get; set; }
        public virtual Engagements Engagement { get; set; }
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
