//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.EF
{
    using System;
    
    public enum StateName : int
    {
        Victoria = 1,
        NewSouthWales = 2,
        Queensland = 3,
        SouthAustralia = 4,
        Tasmania = 5,
        ACT = 6
    }
}
