//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeTrackerModelContainer : DbContext
    {
        public TimeTrackerModelContainer()
            : base("name=TimeTrackerModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Agencies> Agencies { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Consultants> Consultants { get; set; }
        public virtual DbSet<Engagements> Engagements { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
    }
}
